import "../globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import AppLayout from "@/components/Layout/AppLayout";
import Navbar from "@/components/Nav/Navbar";
import Card from "@/components/Card/Card";
import ImagesCard from "@/components/UI/ImagesCard";
import { motion } from "framer-motion";
import AuthLayoutText from "@/components/Card/CardTexts/AuthLayoutText";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-tertiary`}>
        <div className="w-full h-screen flex flex-col">
          <Navbar />
          <div className="w-full bg-tertiary flex  flex-col flex-1 justify-center items-center text-white">
            <div className="w-full lg:max-w-5xl">
              <Card>
                <div className="w-full flex gap-2 ">
                  <div className="flex-1 ">{children}</div>
                  <div className="flex-1 bg-transparent hidden  justify-center items-center lg:flex lg:flex-col">
                    <ImagesCard />
                    <AuthLayoutText />
                  </div>
                </div>
              </Card>
            </div>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
